# Generated by Django 2.1.2 on 2018-10-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_common_name', models.CharField(max_length=200)),
                ('issuer_organization', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('result_color_hex', models.CharField(max_length=100)),
                ('subject_common_name', models.CharField(max_length=100)),
                ('subject_organization', models.CharField(max_length=100)),
                ('validation_result', models.CharField(max_length=100)),
                ('validation_result_short', models.CharField(max_length=5)),
            ],
        ),
    ]
